version: "3.6"

services:
  api:
    build:
      context: ./backend/build/package
      dockerfile: Dockerfile.local
    network_mode: host
    volumes:
      - .:/go/src
    working_dir: /go/src/backend
    tty: true
    depends_on:
      - db

  db:
    image: postgres:16
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - TZ=UTC

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db
