version: "3.6"

services:
  api:
    build:
      context: ./backend/build/package
      dockerfile: Dockerfile.local
    ports:
      - 8000:8000
    volumes:
      - .:/go/src
    working_dir: /go/src/backend
    tty: true
