name: Deploy backend to ghcr.io

on:
  push:
    branches:
      - master
    paths:
      - backend/**
      - .github/workflows/deploy_backend.yml

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ACCESS_TOKEN }}

      - name: Generate environment file
        run: |
          touch .env
          echo "DATABASE_HOST=${{ secrets.DATABASE_HOST }}" >> .env
          echo "DATABASE_PORT=${{ secrets.DATABASE_PORT }}" >> .env
          echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> .env
          echo "DATABASE_USER=${{ secrets.DATABASE_USER }}" >> .env
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> .env
          echo "DATABASE_TIME_ZONE=${{ secrets.DATABASE_TIME_ZONE }}" >> .env

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: backend/build/package/Dockerfile.deploy
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/kaname-backend:latest
            ghcr.io/${{ github.repository_owner }}/kaname-backend:1.0.0
          platforms: linux/amd64,linux/arm64
